#include "anim_macros.h"


BEGIN_FRAMES(PLAYER_IDLE_ANIM_FRAMES)
    FRAME(1, 10)
END_FRAMES(PLAYER_IDLE_ANIM_FRAMES)

ANIM_DATA(
    PLAYER_IDLE_ANIMATION,
    PLAYER_IDLE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    0,
    0
)