#include "anim_macros.h"


#define TILES_OFFSET 21

BEGIN_FRAMES(ENEMY_IDLE_ANIM_FRAMES)
    FRAME(TILES_OFFSET, 10)
END_FRAMES(ENEMY_IDLE_ANIM_FRAMES)

ANIM_DATA(
    ENEMY_IDLE_ANIMATION,
    ENEMY_IDLE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    0,
    0
)