#include "anim_macros.h"


BEGIN_FRAMES(BULLET_BASE_ANIM_FRAMES)
    FRAME(9, 10)
    FRAME(10, 10)
END_FRAMES(BULLET_BASE_ANIM_FRAMES)

BEGIN_FRAMES(MISSILE_BASE_ANIM_FRAMES)
    FRAME(13, 5)
    FRAME(14, 5)
    FRAME(15, 5)
    FRAME(16, 5)
END_FRAMES(MISSILE_BASE_ANIM_FRAMES)

ANIM_DATA(
    BULLET_PLAZMA_ANIMATION,
    BULLET_BASE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    0,
    ANIM_FLAG_LOOP_ON_CREATE | ANIM_FLAG_PLAY_ON_CREATE
)

ANIM_DATA(
    BULLET_LAZER_ANIMATION,
    BULLET_BASE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    2,
    ANIM_FLAG_LOOP_ON_CREATE | ANIM_FLAG_PLAY_ON_CREATE
)
ANIM_DATA(
    BULLET_MISSILE_ANIMATION,
    BULLET_BASE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    4,  // offset
    ANIM_FLAG_LOOP_ON_CREATE | ANIM_FLAG_PLAY_ON_CREATE
)