#include "anim_macros.h"


BEGIN_FRAMES(BULLET_BASE_ANIM_FRAMES)
    FRAME(0, 10)
    FRAME(1, 10)
END_FRAMES(BULLET_BASE_ANIM_FRAMES)

BEGIN_FRAMES(MISSILE_BASE_ANIM_FRAMES)
    FRAME(0, 5)
    FRAME(1, 5)
    FRAME(2, 5)
    FRAME(3, 5)
END_FRAMES(MISSILE_BASE_ANIM_FRAMES)

ANIM_DATA(
    BULLET_PLAZMA_ANIMATION,
    BULLET_BASE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    13,
    ANIM_FLAG_LOOP_ON_CREATE | ANIM_FLAG_PLAY_ON_CREATE
)

ANIM_DATA(
    BULLET_LAZER_ANIMATION,
    BULLET_BASE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    15,
    ANIM_FLAG_LOOP_ON_CREATE | ANIM_FLAG_PLAY_ON_CREATE
)
ANIM_DATA(
    BULLET_MISSILE_ANIMATION,
    BULLET_BASE_ANIM_FRAMES,
    DEFAULT_ANIM_SPEED_SCALE,
    17,  // offset
    ANIM_FLAG_LOOP_ON_CREATE | ANIM_FLAG_PLAY_ON_CREATE
)